import 'package:flutterapp/FaultyEquipmentReport.dart';
import 'package:flutterapp/OutdoorGym.dart';

class Equipment{

  String _name;
  List <FaultyEquipmentReport> _faultyReports;

  //param id shall be changed to something a bit more autogenerated, smart and sexy
  Equipment(String name){
    this._name = name;

  }


  String getName() {
    return _name;
  }


  List getReports(){
    return _faultyReports;
  }

  @override
  String toString() {
    return 'Equipment{_name: $_name}';
  }

}

//class ChinUpBar extends Equipment{
//  int _height;
//  //param id shall be changed to something a bit more autogenerated, smart and sexy
//  ChinUpBar(int id, OutdoorGym location, int height) :
//        _height = height,
//        super(id, location);
//  int getHeight(){
//    return _height;
//  }
//}
//
//class Stump extends Equipment{
//  int _height;
//  //param id shall be changed to something a bit faster, harder, scooter
//  Stump(int id, OutdoorGym location, int height) :
//        _height = height,
//        super(id, location);
//}

